Fix Issue #8936 - [CRIT] ftmod_sangoma_isdn_stack_rcv.c:240 errors in the log during NSG MaxCalls automatic test
Severity change from CRIT to INFO as requested